name: The Universe According To Brett Owers
favicon: null
layout_spectrum: 0.40659546037204564
typography_spectrum: 0.8493131862487644
title: The Universe According To Brett Owers
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.06656098691746593
  lightness: 0.28952019196003675
  saturation: 0.793553710449487
  rhythmicContrast: 0.760619553970173
purpose: []
