typography_spectrum: 0.74526
color:
  brandColors:
    - '#450951'
    - '#ccaacb'
    - '#ebdae0'
    - '#853222'
    - '#9c69b6'
  brandStrength: 1
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: The Universe According To Brett Owers
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Bobo's Universe
purpose: []
